contacts/urls.py
from django.urls import path
from . import views


app_name = 'contacts'

urlpatterns = [
    path('', views.ContactTemplateView.as_view(), name='index'),
    path('list/', views.ContactListView.as_view(), name='list'),
    path('add/', views.ContactCreateView.as_view(), name='add'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contacts.urls')),
]

contacts/models.py
from django.db import models
from django.utils.translation import gettext as _


class Contact(models.Model):
    name = models.CharField(_('Name'), max_length=50)
    email = models.EmailField(_('email'))

    def __str__(self):
        return self.name

contacts/views.py
from django.shortcuts import render
from django.views import generic
from .models import Contact


class ContactTemplateView(generic.TemplateView):
    template_name = "contacts/options.html"


class ContactListView(generic.ListView):
    model = Contact
    template_name = 'contacts/list.html'


class ContactCreateView(generic.CreateView):
    model = Contact
    fields = ['name', 'email']
    template_name = 'contacts/add.html'
    success_url='/list'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

templates/contacts/add.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'Add' %}{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        
        {{ form.non_field_errors }}
        
        <label for="name">{% trans 'Name' %}</label>
        {{ form.name }}
        {{ form.name.errors }}
        
        <br>

        <label for="email">{% trans 'Email' %}</label>
        {{ form.email }}
        {{ form.email.errors }}

        <br>
        
        <a href="{% url 'contacts:index' %}">{% trans 'Back' %}</a>
        <button type="submit">{% trans 'Save' %}</button>
    </form>
{% endblock %}

templates/contacts/list.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'List' %}{% endblock %}

{% block content %}
    {% for contact in object_list %}
        <p>{{ contact.name }} - {{ contact.email }}</p>
    {% empty %}
        {% trans 'No contacts!' %}
    {% endfor %}
    <a href="{% url 'contacts:index' %}">{% trans 'Back' %}</a>
{% endblock %}

templates/contacts/options.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'Options' %}{% endblock %}

{% block content %}
<p><a href="{% url 'contacts:list' %}">{% trans 'List' %}</a></p>
<p><a href="{% url 'contacts:add' %}">{% trans 'Add' %}</a></p>
{% endblock %}